###############################################################
#######################Powered By Bubble#######################
##########################Author:绿毛###########################
###############################################################
Time: 7 #这个数字不应该超过10
Success: "&aSuccess!Plz relogin!"
Failed: "&cWrong code..."
KickOut: "&cOut of time..."
Messages:
  - "&7Enter the code plz:"
  - "&7Read the code on the map!"
  - "&7Type them in the chat bar!"
  - "&7Only have 7 second to finish it."
LegalPlayers: