###############################################################
#######################Powered By Bubble#######################
##########################Author:绿毛###########################
###############################################################
Time: 7 #这个数字不应该超过10
KickOut: "&c你超时未完成验证……"
Messages:
  - "&7由于您是第一次进入服务器，请输入一次验证码:"
  - "&7阅读地图上的条形码，并在聊天栏里输入这两个字!"
  - "&7你有 7 秒的时间完成输入……"
LegalPlayers: